[phases.setup]
nixPkgs = ["python3", "gcc", "cmake", "libopenblas", "lapack"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --no-cache-dir -r requirements.txt"
]

[phases.start]
cmd = "./start.sh"